### ISSUE TITLE
Migration table not found.

### ISSUE THREAD

**Issue by deepesh08** [ant-vel/Discussion#20]
php artisan key:generate

                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '  
  /var/run/mysqld/mysqld.sock' (2)                                             
                                                                               

s3india2@s3india2:/opt/lampp/htdocs/antVel$ php artisan key:generate

                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '  
  /var/run/mysqld/mysqld.sock' (2)                                             
                                                                               

s3india2@s3india2:/opt/lampp/htdocs/antVel$ php artisan key:generate

                                                                               
  [ErrorException]                                                             
  file_get_contents(/opt/lampp/htdocs/antVel/.env): failed to open stream: No  
   such file or directory                                                      
                                                                               

s3india2@s3india2:/opt/lampp/htdocs/antVel$ php artisan key:generate
Application key [base64:P+HrWYzYFY8SuALGTXsgkKSHXalO6+gFhtivSsYx36w=] set successfully.
s3india2@s3india2:/opt/lampp/htdocs/antVel$ ^C
s3india2@s3india2:/opt/lampp/htdocs/antVel$ ^C
s3india2@s3india2:/opt/lampp/htdocs/antVel$ ^C
s3india2@s3india2:/opt/lampp/htdocs/antVel$ ^C
s3india2@s3india2:/opt/lampp/htdocs/antVel$ sudo composer install
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
s3india2@s3india2:/opt/lampp/htdocs/antVel$ php artisan migrate:refresh
Migration table not found.
Migration table created successfully.

                                                                               
  [Illuminate\Database\QueryException]                                         
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MariaDB server  
   version for the right syntax to use near 'json null, `remember_token` varc  
  har(100) null, `created_at` timestamp null, `upd' at line 1 (SQL: create ta  
  ble `users` (`id` int unsigned not null auto_increment primary key, `nickna  
  me` varchar(255) not null, `email` varchar(255) not null, `password` varcha  
  r(60) not null, `pic_url` varchar(255) null, `language` varchar(255) not nu  
  ll default 'en', `mobile_phone` varchar(255) null, `work_phone` varchar(255  
  ) null, `website` varchar(255) null, `twitter` varchar(255) null, `facebook  
  ` varchar(255) null, `description` varchar(255) null, `time_zone` varchar(2  
  55) null, `rate_val` int null, `rate_count` int null, `role` enum('admin',   
  'business', 'person') not null default 'person', `type` enum('normal', 'tru  
  sted') not null default 'normal', `verified` enum('yes', 'no') not null def  
  ault 'no', `preferences` json null, `remember_token` varchar(100) null, `cr  
  eated_at` timestamp null, `updated_at` timestamp null, `disabled_at` timest  
  amp null, `deleted_at` timestamp null) default character set utf8 collate u  
  tf8_unicode_ci)

**Comment by napestershine** [comment]
Use Mysql 5.7 and that will fix it.
