### ISSUE TITLE
Split route file in small files to separate by module or other logic

### ISSUE THREAD

**Issue by Artessan** [ant-vel/Discussion#23]
I think is good idea split the route file in small files by module or ligic, In that way is more esay read, check or modify the routes for a specfic task.

We can use a config/route file to load the routes files and use a Http/Routes to storage this files.

**Comment by gocanto** [comment]
if you are willing to send the PR i can tell you how exactly I would like it to be.

**Comment by Artessan** [comment]
i have one ready, check this https://github.com/ant-vel/antVel/compare/development...Artessan:AV-2, maybe this is good or we can use your idea

**Comment by gocanto** [comment]
I like it, but I do not like the idea of having another file into the config folder. 

How I do it is like this: 

* Create a ```route``` folder as you have it
* Place the route separated by modules, as you do as well. 
* Include the files into the ```Route.php``` file that comes with laravel, as so: 

```php
require __DIR__ . '/Routes/landing.php';

require __DIR__ . '/Routes/dashboard.php';
```

Do you get the idea?

**Comment by Artessan** [comment]
ok, yeah a I got it, then this not required a PR, with the refact of the modules we can move the routes part  to part in this way.

Other thing out of this, yesterday i have some issues with bower install and the angular version. I know you want moving out to vue but right now is a problem if any want try to install. this required a new issue in the antvel/antvel repo?

**Comment by gocanto** [comment]
I am aware of it and that is one of the main reason I wanna move it over to vue. The thing is I need help and I cannt do much by myself right now.

**Comment by gocanto** [comment]
that would be awesome. I can give you access to the scrum area and divide the task. So far, we just can move everything to vue. Then, we could thing of working in backend refactoring.

**Comment by Artessan** [comment]
yeah, that sound good.

**Comment by gocanto** [comment]
Cool.

Drop off your email and I ll send the invitation to you. 

where are you from btw?

**Comment by Artessan** [comment]
Vzla. casanova21c@gmail.com

**Comment by gocanto** [comment]
Cool. Yo soy the Valencia vzla as well!

**Comment by Artessan** [comment]
Nice! (fino)

**Comment by gocanto** [comment]
done!

**Comment by gocanto** [comment]
I did it through taiga, but I would like to see if we can keep the modifications public here somehow. I ll find out and let u know.

**Comment by Artessan** [comment]
yeah, I'm in, well i think the best way is make a road map and maintain the discussion like a point to get oppinions and explaint  the future or actual changes

**Comment by gocanto** [comment]
I have been trying to do that since I pushed antvel as free, but people don't get involved.

**Comment by Artessan** [comment]
the start is complicate, in some point of the road maybe change or maybe not

**Comment by gocanto** [comment]
alright dude, let's see what we can do then. You have my email, you can add to any chat services you use and we can talk through it. I use slack a lot!

**Comment by Artessan** [comment]
yeah me too, i saw you have a channel maybe add me there and can be the best way to planificate

**Comment by gocanto** [comment]
I sent the inv, let me know if u got it
